-- Typical table definitions for the YDB Key Prefix Demo tool

CREATE TABLE `key_prefix_demo/main` (
  id Uuid NOT NULL,
  id_text Text NOT NULL,
  collection_id Uuid,
  tv Timestamp,
  ballast1 Text,
  PRIMARY KEY (id),
  INDEX ix_text GLOBAL SYNC ON (id_text),
  INDEX ix_tv GLOBAL SYNC ON (tv),
  INDEX ix_coll GLOBAL SYNC ON (collection_id)
) WITH (
  AUTO_PARTITIONING_BY_SIZE = ENABLED,
  AUTO_PARTITIONING_BY_LOAD = ENABLED,
  AUTO_PARTITIONING_PARTITION_SIZE_MB = 1000,
  AUTO_PARTITIONING_MIN_PARTITIONS_COUNT = 5000,
  AUTO_PARTITIONING_MAX_PARTITIONS_COUNT = 5500
);

CREATE TABLE `key_prefix_demo/sub` (
  id Uuid NOT NULL,
  ref_id Uuid,
  tv Timestamp,
  ballast2 Text,
  PRIMARY KEY (id),
  INDEX ix_tv GLOBAL SYNC ON (tv),
  INDEX ix_ref GLOBAL SYNC ON (ref_id)
) WITH (
  AUTO_PARTITIONING_BY_SIZE = ENABLED,
  AUTO_PARTITIONING_BY_LOAD = ENABLED,
  AUTO_PARTITIONING_PARTITION_SIZE_MB = 1000,
  AUTO_PARTITIONING_MIN_PARTITIONS_COUNT = 5000,
  AUTO_PARTITIONING_MAX_PARTITIONS_COUNT = 5500
);

ALTER TABLE `key_prefix_demo/main` ALTER INDEX ix_coll SET (
  AUTO_PARTITIONING_BY_SIZE = ENABLED,
  AUTO_PARTITIONING_BY_LOAD = ENABLED,
  AUTO_PARTITIONING_PARTITION_SIZE_MB = 500,
  AUTO_PARTITIONING_MIN_PARTITIONS_COUNT = 1000,
  AUTO_PARTITIONING_MAX_PARTITIONS_COUNT = 1100
);

ALTER TABLE `key_prefix_demo/main` ALTER INDEX ix_text SET (
  AUTO_PARTITIONING_BY_SIZE = ENABLED,
  AUTO_PARTITIONING_BY_LOAD = ENABLED,
  AUTO_PARTITIONING_PARTITION_SIZE_MB = 500,
  AUTO_PARTITIONING_MIN_PARTITIONS_COUNT = 1000,
  AUTO_PARTITIONING_MAX_PARTITIONS_COUNT = 1100
);

ALTER TABLE `key_prefix_demo/main` ALTER INDEX ix_tv SET (
  AUTO_PARTITIONING_BY_SIZE = ENABLED,
  AUTO_PARTITIONING_BY_LOAD = ENABLED,
  AUTO_PARTITIONING_PARTITION_SIZE_MB = 500,
  AUTO_PARTITIONING_MIN_PARTITIONS_COUNT = 1000,
  AUTO_PARTITIONING_MAX_PARTITIONS_COUNT = 1100
);

ALTER TABLE `key_prefix_demo/sub` ALTER INDEX ix_ref SET (
  AUTO_PARTITIONING_BY_SIZE = ENABLED,
  AUTO_PARTITIONING_BY_LOAD = ENABLED,
  AUTO_PARTITIONING_PARTITION_SIZE_MB = 500,
  AUTO_PARTITIONING_MIN_PARTITIONS_COUNT = 1000,
  AUTO_PARTITIONING_MAX_PARTITIONS_COUNT = 1100
);

ALTER TABLE `key_prefix_demo/sub` ALTER INDEX ix_tv SET (
  AUTO_PARTITIONING_BY_SIZE = ENABLED,
  AUTO_PARTITIONING_BY_LOAD = ENABLED,
  AUTO_PARTITIONING_PARTITION_SIZE_MB = 500,
  AUTO_PARTITIONING_MIN_PARTITIONS_COUNT = 1000,
  AUTO_PARTITIONING_MAX_PARTITIONS_COUNT = 1100
);
